<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MissTortas.Data\MissTortas.Domain.csproj" />
    <ProjectReference Include="..\MissTortas.Domain\MissTortas.Domain.csproj" />
    <ProjectReference Include="..\MissTortas.Repository\MissTortas.Repository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Security\" />
  </ItemGroup>

</Project>
