// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissTortas.Infrastructure.Context;

#nullable disable

namespace MissTortas.Infrastructure.Migrations
{
    [DbContext(typeof(MissTortasContext))]
    [Migration("20260405131103_InitialCreate1.0")]
    partial class InitialCreate10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.OrderType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderTypes");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.PaymentMethodDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("PaymentMethodDetails");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PaymentMethodDetail");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.PaymentRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("PaymentRequests");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.PersonalizedProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float>("FinalPrice")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductImageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductImageId");

                    b.ToTable("PersonalizedProduct");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFiles");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Resource", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Resource");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Right", b =>
                {
                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<bool>("Constraint")
                        .HasColumnType("bit");

                    b.Property<bool>("Transferable")
                        .HasColumnType("bit");

                    b.HasKey("SubjectId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Rights");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Entity.Orders.ConsultancyFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultancyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultancyId");

                    b.ToTable("ConsultancyFiles");
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Security.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Security.Identity.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasIndex("RoleId")
                        .IsUnique()
                        .HasFilter("[RoleId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.CreditCardDetail", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Payments.PaymentMethodDetail");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CardHolderName");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN");

                    b.HasDiscriminator().HasValue("CreditCardDetail");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.DebitCardDetail", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Payments.PaymentMethodDetail");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CardHolderName");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExpirationDate");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAN");

                    b.HasDiscriminator().HasValue("DebitCardDetail");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Consultancy", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint");

                    b.Property<string>("BakeryNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Consultancies");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Order", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<long>("ConsultancyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<long>("PaymenRequestId")
                        .HasColumnType("bigint");

                    b.HasIndex("ConsultancyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.OrderPreparation", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FinalizationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.HasIndex("AssigneeId");

                    b.ToTable("OrderPreparations");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.OrderSaleProduct", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("QuantityAsked")
                        .HasColumnType("float");

                    b.Property<long>("SaleProductId")
                        .HasColumnType("bigint");

                    b.HasIndex("SaleProductId");

                    b.HasIndex("OrderId", "SaleProductId");

                    b.ToTable("AskedProducts");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.Payment", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentRequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.HasIndex("PaymentRequestId")
                        .IsUnique()
                        .HasFilter("[PaymentRequestId] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.Category", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.Product", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Resource");

                    b.Property<bool>("ManageQuantityAsInteger")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Users.Role", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Subject");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DomainRoles");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Users.User", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Security.Authorization.Subject");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DomainUsers");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductCategory", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Products.Category");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.SaleProduct", b =>
                {
                    b.HasBaseType("MissTortas.Domain.Products.Product");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.ToTable("SaleProducts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MissTortas.Infrastructure.Security.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MissTortas.Infrastructure.Security.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Infrastructure.Security.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MissTortas.Infrastructure.Security.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.PaymentMethodDetail", b =>
                {
                    b.HasOne("MissTortas.Domain.Payments.Payment", "Payment")
                        .WithOne("PaymentMethodDetail")
                        .HasForeignKey("MissTortas.Domain.Payments.PaymentMethodDetail", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.PaymentRequest", b =>
                {
                    b.HasOne("MissTortas.Domain.Orders.Order", "Order")
                        .WithOne("PaymentRequest")
                        .HasForeignKey("MissTortas.Domain.Payments.PaymentRequest", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.PersonalizedProduct", b =>
                {
                    b.HasOne("MissTortas.Domain.Orders.Order", null)
                        .WithMany("PersonalizedProducts")
                        .HasForeignKey("OrderId");

                    b.HasOne("MissTortas.Domain.Products.ProductFile", "ProductImage")
                        .WithMany()
                        .HasForeignKey("ProductImageId");

                    b.Navigation("ProductImage");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductFile", b =>
                {
                    b.HasOne("MissTortas.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Right", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", "Resource")
                        .WithMany("Rights")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Authorization.Subject", "Subject")
                        .WithMany("Rights")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Entity.Orders.ConsultancyFile", b =>
                {
                    b.HasOne("MissTortas.Domain.Orders.Consultancy", "Consultancy")
                        .WithMany()
                        .HasForeignKey("ConsultancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultancy");
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Security.Identity.ApplicationUser", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("MissTortas.Infrastructure.Security.Identity.ApplicationUser", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Infrastructure.Security.Identity.ApplicationRole", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Users.Role", "Role")
                        .WithOne()
                        .HasForeignKey("MissTortas.Infrastructure.Security.Identity.ApplicationRole", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Consultancy", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Users.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Users.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Orders.Consultancy", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Order", b =>
                {
                    b.HasOne("MissTortas.Domain.Orders.Consultancy", "Consultancy")
                        .WithMany("Orders")
                        .HasForeignKey("ConsultancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Orders.Order", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultancy");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.OrderPreparation", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Users.User", "Assignee")
                        .WithMany("Preparations")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Orders.Order", "Order")
                        .WithMany("Preparations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Orders.OrderPreparation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.OrderSaleProduct", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Orders.OrderSaleProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Orders.Order", "Order")
                        .WithMany("ProductsAsked")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Products.SaleProduct", "SaleProduct")
                        .WithMany()
                        .HasForeignKey("SaleProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SaleProduct");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.Payment", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Payments.Payment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Payments.PaymentRequest", "PaymentRequest")
                        .WithOne("Payment")
                        .HasForeignKey("MissTortas.Domain.Payments.Payment", "PaymentRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.Category", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Products.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Products.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.Product", b =>
                {
                    b.HasOne("MissTortas.Domain.Products.ProductDetail", "ProductDetail")
                        .WithOne("Product")
                        .HasForeignKey("MissTortas.Domain.Products.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Security.Authorization.Resource", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Products.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissTortas.Domain.Products.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Users.Role", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Subject", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Security.Users.Role", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Users.User", b =>
                {
                    b.HasOne("MissTortas.Domain.Security.Authorization.Subject", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Security.Users.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductCategory", b =>
                {
                    b.HasOne("MissTortas.Domain.Products.Category", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Products.ProductCategory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Domain.Products.SaleProduct", b =>
                {
                    b.HasOne("MissTortas.Domain.Products.Product", null)
                        .WithOne()
                        .HasForeignKey("MissTortas.Domain.Products.SaleProduct", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.PaymentRequest", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductDetail", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Resource", b =>
                {
                    b.Navigation("Rights");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Authorization.Subject", b =>
                {
                    b.Navigation("Rights");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Consultancy", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MissTortas.Domain.Orders.Order", b =>
                {
                    b.Navigation("PaymentRequest");

                    b.Navigation("PersonalizedProducts");

                    b.Navigation("Preparations");

                    b.Navigation("ProductsAsked");
                });

            modelBuilder.Entity("MissTortas.Domain.Payments.Payment", b =>
                {
                    b.Navigation("PaymentMethodDetail");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MissTortas.Domain.Security.Users.User", b =>
                {
                    b.Navigation("Preparations");
                });

            modelBuilder.Entity("MissTortas.Domain.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
