<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ServiceClient\**" />
    <Content Remove="Services\ServiceClient\**" />
    <EmbeddedResource Remove="Services\ServiceClient\**" />
    <None Remove="Services\ServiceClient\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\DTO\" />
    <Folder Include="Services\Users\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.1" />
  </ItemGroup>

</Project>
