<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\Products\formCreateSaleProduct.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Products\formSaleProductsFromCategory.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Roles\formCreateRole.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Roles\formEditRole.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\Roles\formRoles.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>